import Header from "@/components/Shared/Header";
import { cn } from "@/utils/classnames";
import "@/styles/globals.scss";
import styles from "./layout.module.scss";

import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AudioStreaming",
  description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, styles.Container)}>
        <Header />
        {children}
      </body>
    </html>
  );
}
